# Generated by Django 5.1.1 on 2024-10-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the gallery.', max_length=150, verbose_name='Gallery Name')),
                ('image', models.ImageField(help_text='Upload an image for the gallery.', upload_to='media/images/', verbose_name='Image')),
                ('description', models.CharField(help_text='Enter a brief description of the gallery.', max_length=500, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Enter your email address.', max_length=254, verbose_name='Email Address')),
                ('subject', models.CharField(help_text='Enter the subject of your message.', max_length=500, verbose_name='Subject')),
                ('message', models.TextField(help_text='Enter your message.', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-id'],
            },
        ),
    ]
